name: Bundle NPM Release

on:
  workflow_call:
    secrets:
      RELEASE_APP_KEY:
        required: true

jobs:
  call-npm-release:
    uses: Forsakringskassan/.github/.github/workflows/npm-release.yaml@main
    secrets:
      RELEASE_APP_KEY: ${{ secrets.RELEASE_APP_KEY }}
  call-npm-ghpages-docs:
    uses: Forsakringskassan/.github/.github/workflows/npm-ghpages-docs.yaml@main
  call-npm-lint:
    uses: Forsakringskassan/.github/.github/workflows/npm-lint.yaml@main
